### ISSUE TITLE
Can not install Humanizer with nuget on VS2015 Beta

### ISSUE THREAD

**Issue by hazzik** [MehdiK/Humanizer#302]
How to reproduce:

1. Install VS2014 CTP

2. Create a new "XXX vNext project" (Console vNext appliation  is just fine)

3. Add Humanizer to the project.json

  ```json
  {
      "dependencies": {
          "Humanizer": "1.26.1"
      },

      "configurations" : {
          "net45" : { },
          "k10" : { 
              "dependencies": {
                  "System.Console": "4.0.0.0"
              }
          }
      }
  }
  ```

4. Build
    
  It says that '_._' is wrong assembly

```text
    Error	1	The command ""C:\Users\hazzik\.kre\packages\kre-svr50-x86.0.1-alpha-build-0446\bin\klr.exe" "C:\Users\hazzik\.kre\packages\kre-svr50-x86.0.1-alpha-build-0446\bin\lib\Microsoft.Framework.Project\Microsoft.Framework.Project.dll" build --check "C:\Users\hazzik\Documents\Visual Studio 14\Projects\ConsoleApp1\ConsoleApp1"" exited with code -1.	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets	124	5	ConsoleApp1
```

```text
------ Build started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
  System.BadImageFormatException: Could not load file or assembly '_._' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  File name: '_._' ---> System.BadImageFormatException: Could not load file or assembly '_._' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  File name: '_._'
  
  
     at System.Reflection.AssemblyName.nGetFileInformation(String s)
     at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
     at Microsoft.Framework.Runtime.NuGetDependencyResolver.GetAssemblyName(String fileName)
     at Microsoft.Framework.Runtime.NuGetDependencyResolver.Initialize(IEnumerable`1 packages, FrameworkName targetFramework)
     at Microsoft.Framework.Runtime.WalkContext.Populate(FrameworkName frameworkName, IList`1 libraries)
     at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramework)
     at Microsoft.Framework.Project.BuildManager.PrepareCompiler(Project project, FrameworkName targetFramework)
     at Microsoft.Framework.Project.BuildManager.CheckDiagnostics(Project project, FrameworkName targetFramework, List`1 diagnostics)
     at Microsoft.Framework.Project.BuildManager.Build()
  
  
  
  Build succeeded.
      0 Warnings(s)
      0 Error(s)
  
  Time elapsed 00:00:05.3851980
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets(124,5): error MSB3073: The command ""C:\Users\hazzik\.kre\packages\kre-svr50-x86.0.1-alpha-build-0446\bin\klr.exe" "C:\Users\hazzik\.kre\packages\kre-svr50-x86.0.1-alpha-build-0446\bin\lib\Microsoft.Framework.Project\Microsoft.Framework.Project.dll" build --check "C:\Users\hazzik\Documents\Visual Studio 14\Projects\ConsoleApp1\ConsoleApp1"" exited with code -1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by onovotny** [comment]
I'm going to close this out as it's been a long time. Please reopen if it's still an issue with the latest RTM VS bits and DNX beta 8.
