### ISSUE TITLE
The type initializer for 'Humanizer.Configuration.Configurator' threw an exception.

### ISSUE THREAD

**Issue by yenelcs** [MehdiK/Humanizer#373]
System.TypeInitializationException: The type initializer for 'Humanizer.Configuration.Configurator' threw an exception. ---> System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
zh-CHS is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at Humanizer.Configuration.FormatterRegistry.RegisterDefaultFormatter(String localeCode)
   at Humanizer.Configuration.FormatterRegistry..ctor()
   at Humanizer.Configuration.Configurator..cctor()
   --- End of inner exception stack trace ---
   at Humanizer.TimeSpanHumanizeExtensions.<gettimeparts>d__4.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<takeiterator>d__3a`1.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, Boolean countEmptyUnits, CultureInfo culture)
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, CultureInfo culture)
   at Flashlight.MainPage.SetBatteryText(Int32 remainingChargePercent, TimeSpan remainingDischargeTime)
   at Flashlight.MainPage.LoadUIComponents()
   at Flashlight.MainPage.<startuicheckthread>b__2d()
--- Inner exception of type System.Globalization.CultureNotFoundException start ---
--- Message: Culture is not supported. Parameter name: name zh-CHS is an invalid culture identifier. ---
System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
zh-CHS is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at Humanizer.Configuration.FormatterRegistry.RegisterDefaultFormatter(String localeCode)
   at Humanizer.Configuration.FormatterRegistry..ctor()
   at Humanizer.Configuration.Configurator..cctor()
--- End of inner exception stack trace ---

**Comment by MehdiK** [comment]
Thanks for reporting this. This is really strange. 

The error says zh-CHS can't be used as a culture identifier, and `CultureInfo` constructor is throwing on that code while there are [passing unit tests in the solution](https://github.com/MehdiK/Humanizer/blob/master/src/Humanizer.Tests/Localisation/zh-CHS/DateHumanizeTests.cs#L8) that are instantiating `CultureInfo` for zh-CHS!!

Is that the locale you're using? Would you be able to send a failing test for this issue?

**Comment by yenelcs** [comment]
zh-CHS and zh-CHT are legacy and it throws exception when you run on Windows phone. You must be running test on the PC. It passes on the PC but fails on the phone. 

https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.parent
Specific cultures should be use instead of legacy ones.

**Comment by MehdiK** [comment]
I fixed that in #374 and it's now been released to NuGet. Please check if it's fixed now.

**Comment by yenelcs** [comment]
It works fine now. Thanks.

**Comment by MehdiK** [comment]
Thanks for reporting and for the link to right culture codes.
