### ISSUE TITLE
Null Reference Exception - DateTime

### ISSUE THREAD

**Issue by MattDavies** [MehdiK/Humanizer#445]
Getting the following in 1.37.0 when calling .Humanize() on a regular DateTime.

Will find the exact data later today, just wanted to log this and make sure it wasn't already known.

    System.NullReferenceException: Object reference not set to an instance of an object.
       at Humanizer.Inflections.Vocabulary.ApplyRules(IList`1 rules, String word)
       at Humanizer.Inflections.Vocabulary.Pluralize(String word, Boolean inputIsKnownToBeSingular)
       at Humanizer.ToQuantityExtensions.ToQuantity(String input, Int32 quantity, ShowQuantityAs showQuantityAs, String format, IFormatProvider formatProvider)
       at Humanizer.Localisation.ResourceKeys.DateHumanize.GetResourceKey(TimeUnit timeUnit, Tense timeUnitTense, Int32 count)
       at Humanizer.Localisation.Formatters.DefaultFormatter.DateHumanize(TimeUnit timeUnit, Tense timeUnitTense, Int32 unit)
       at Humanizer.DateTimeHumanizeStrategy.DateTimeHumanizeAlgorithms.DefaultHumanize(DateTime input, DateTime comparisonBase, CultureInfo culture)
       at Humanizer.DateTimeHumanizeStrategy.DefaultDateTimeHumanizeStrategy.Humanize(DateTime input, DateTime comparisonBase, CultureInfo culture)
       at Humanizer.DateHumanizeExtensions.Humanize(DateTime input, Boolean utcDate, Nullable`1 dateToCompareAgainst, CultureInfo culture)

**Comment by bmdixon** [comment]
I'm experiencing the same error when calling .Humanize() on a DateTimeOffset.UtcDateTime. Rolled back to 1.36 and it no longer errors.

**Comment by MehdiK** [comment]
Thanks for reporting @MattDavies. This may have already been fixed in #439.

**Comment by MattDavies** [comment]
Yep, that PR definitely looks like it would resolve the issue.

Thanks Mehdi

**Comment by bmdixon** [comment]
Any idea when this fix will get released?

**Comment by MehdiK** [comment]
Sorry for the delay. I'll try to release it today, fingers crossed.

**Comment by MehdiK** [comment]
Fixed by #439.

**Comment by MehdiK** [comment]
This is now released to Nuget as v1.37.7. Please let me know if the bug is still there. Thanks.

**Comment by MattDavies** [comment]
Thanks @MehdiK, legend!
